### ISSUE TITLE
Issue with plotting using A2E_app in MATLAB (2024a)

### ISSUE THREAD

**Issue by chronictectonic** [yuntao-github/A2E_app#1]
I am using the A2E app from this repository and am having issues with plotting the output from the test data. I receive several error messages - seemingly associated with the "othercolor" folder.

I attach the error messages. Please let me know how to proceed.

Best,
Stephanie
<img width="894" alt="Screenshot 2024-08-02 at 12 41 21 PM" src="https://github.com/user-attachments/assets/ba3fbb14-e315-4452-9145-47ac3375edd4">

**Comment by chronictectonic** [comment]
![untitled](https://github.com/user-attachments/assets/28a252c5-4dc1-4419-aab7-5c20f2a5e873)

That is what I get (incomplete)

**Comment by yuntao-github** [comment]
It seems the MATLAB did not find the "/othercolor/othercolor/colorData.mat" file, which defines the colors to be used for plotting the resolution and correlation matrix. Just updated the "A2E_App.mlapp" script. Please give it a go. Thanks for your interest.

**Comment by chronictectonic** [comment]
Hello,

Thanks for looking into it. It seems now there is a new issue: the code doesn't run now. I think there is an error in the path being called.

Thanks,
Stephanie
<img width="909" alt="Screenshot 2024-08-05 at 10 59 27 AM" src="https://github.com/user-attachments/assets/76da43d4-5e9e-4782-96a3-ca1dbbe916f1">

**Comment by yuntao-github** [comment]
It seems to be an issue with the directory that you put the files. The code runs ok on my side. Please try it again.

**Comment by chronictectonic** [comment]
OK, I will try it but have you tested it on a different machine also? Sometimes it works because the directory is local/unique to the machine on which you are testing but it's not transferable to others.

**Comment by chronictectonic** [comment]
As I suspected, it did not resolve the issue:

If you look at the error message it seems to be inserting the path in the incorrect order, so instead of 'path/to/file/DATA_Fitzgerald1995.csv' it's going out of order: 'Fitzgerald1995/DATA_/path/to/file/Fitzgerald1995.csv'

**Comment by chronictectonic** [comment]
Hello,

We thought perhaps I needed an additional add-on for Matlab (since it seems to be working for my colleague). I tested this (using the version that runs just doesn't plot fully) and it did not resolve the issue. Just wanted to let you know.

Thanks,
Stephanie

**Comment by chronictectonic** [comment]
OK, it seems I didn't have everything together (just the GUI folder) and it needed all three folders from this repository. It runs now, thanks!
